### ISSUE TITLE
V1.3.1 causes different TSC rules to be applied than project settings

### ISSUE THREAD

**Issue by JakeStanger** [Voitanos/jest-preset-spfx-react16#11]
The change to the config to use the custom `tsconfig.json` causes the transpiler rules to (very likely) mismatch those of the project using the preset, and do not match the rules of a scaffolded SPFx project. 

The result of this is that tests will throw a multitude of errors when transpiling from TS(X) -> JS that do not occur when building the project.

**Comment by andrewconnell** [comment]
There's a PR #10 to address this... I plan to incorporate it in the next two days...

**Comment by JakeStanger** [comment]
Should have checked 🤦‍♂ sorry
