### ISSUE TITLE
jest-preset.json testMatch Question

### ISSUE THREAD

**Issue by juliemturner** [Voitanos/jest-preset-spfx-react16#12]
I have a question about the testMatch pattern: 
`**/__tests_ _/**/*.(spec|test).+(ts|js)?(x)`

My google-fu may be failing me but I couldn't find any reference to a glob pattern using _ in them, and I am wondering if this is a Windows vs Mac issue.  My intent was to have a "tests" folder not keep my tests in the src folder (for various reasons that don't really matter). If the folder should really be named __tests__ that then (in Windows) hides the folder from Visual Studio Code and jest won't find the tests. If I name it 'tests' then this pattern won't find it. I obviously can add the pattern for tests and have done so but wondered if I was missing something obvious.

Thanks for this great solution it really got me up and running fast!

**Comment by andrewconnell** [comment]
What are the actual suites (files) named? Can you share an example of your full path? 

This should work for the following:
- `/tests/something.spec.tsx`
- `/tests/folder/something.spec.tsx`
- either of the above with "test" instead of "spec" in the name
- either of the above for JSX files
- either of the above with additional nested folders

**Comment by juliemturner** [comment]
yes, so an actual example file is:
`/tests/common/services/UpgradeServices.spec.ts`

The provided jest-preset.json file specifies the following
`
"testMatch": [
    "**/src/**/*.(spec|test).+(ts|js)?(x)",
    "**/__tests__/**/*.(spec|test).+(ts|js)?(x)"
  ],
`
That setup will not find my above file on windows. However, if I adjust it to the following it works fine:
`
"testMatch": [
    "**/src/**/*.(spec|test).+(ts|js)?(x)",
    "**/tests/**/*.(spec|test).+(ts|js)?(x)",
    "**/__tests__/**/*.(spec|test).+(ts|js)?(x)"
  ],
`
I was basically trying to verify that my assumption that `__tests__` was indeed a pattern that should match the root folder tests as a sibling of src. What I'm wondering is if this is a limitation of mac vs windows.

**Comment by andrewconnell** [comment]
It's not finding it because your folder is named `tests`, not `__tests__`

**Comment by juliemturner** [comment]
Actually, I tried that first, thinking it was literal an not a pattern and that doesn't work. I just retested it again to make sure, also copied the value `__tests__` to make sure there is no encoding problem as I've had that bite me with PowerShell.

To to be clear this path also doesn't work:
`__tests__/common/services/UpgradeServices.spec.ts`

**Comment by juliemturner** [comment]
My current workaround, that's good for anyone else to know in case they have a requirement that their tests be in some folder way outside the patterns you support, is to add an entry into the jest.config.json file in the config folder... so this:

`{`
`  "preset": "@voitanos/jest-preset-spfx-react16",`
`  "rootDir": "../tests",`
`  "testMatch": [`
`    "**/tests/**/*.(spec|test).+(ts|js)?(x)"`
`  ]`
`}`

**Comment by andrewconnell** [comment]
`_` isn't a special character in regex... just a string. 

Most developers when writing tests put them either beside the code they test (ie: `src`) or in a `__tests__` folder as that pattern matches the folders generated by snapshots when doing React component rendering tests.

If you want to have your tests in a folder separate from your source, just override the **testMatch** property defined in the preset. If you wanted it to be either "src" or "tests", set the contents of **jest.config.json** to:

```json
{
  "preset": "@voitanos/jest-preset-spfx-react16",
  "rootDir": "../tests",
  "testMatch": [
    "**/(src|tests)/**/*.(spec|test).+(ts|js)?(x)"
  ]
}
```

**Comment by juliemturner** [comment]
Yep, well... for whatever reason I can't use the folder `__tests__` so... it's what it is... and I had applied the workaround...  thanks for the confirmation.
