### ISSUE TITLE
Problem when using WebPartTitle component

### ISSUE THREAD

**Issue by Leif-Frederiksen** [Voitanos/jest-preset-spfx-react16#2]
I get a problem when I have a component that uses the WebPartTitle component (part of the @pnp/spfx-controls-react project).

In that case I get this error when running the test:
```
● Test suite failed to run

Cannot find module 'ControlStrings' from 'WebPartTitle.js'

at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:169:17)
at Object.<anonymous> (../node_modules/@pnp/spfx-controls-react/lib/controls/webPartTitle/WebPartTitle.js:14:15)

```
Any ideas on how to resolve this problem?

**Comment by andrewconnell** [comment]
Update - I understand *why* this is happening, but I can't figure out how to fix it for a bigger set of circumstances. 

It's easy to fix for just the one library you're using, but this will quickly turn into a +1 issue when someone uses another library, so I'm looking for a more dynamic solution... this is affecting all three of my presets... 

Still working...

**Comment by andrewconnell** [comment]
I'm going to close this issue... I'm not entirely sure how to handle this. The challenge is that SPFx is loading that module on demand on the page (see the `config.json` folder)... so you somehow have to tell Jest where to find that module. Not sure how this would be done... sorry :(
